/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as AuthenticatedUserIndexRouteImport } from './routes/_authenticated/user/index'
import { Route as AuthenticatedPanelIndexRouteImport } from './routes/_authenticated/panel/index'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUserIndexRoute = AuthenticatedUserIndexRouteImport.update({
  id: '/user/',
  path: '/user/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPanelIndexRoute = AuthenticatedPanelIndexRouteImport.update({
  id: '/panel/',
  path: '/panel/',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/panel/': typeof AuthenticatedPanelIndexRoute
  '/user/': typeof AuthenticatedUserIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/panel': typeof AuthenticatedPanelIndexRoute
  '/user': typeof AuthenticatedUserIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth/sign-in': typeof AuthSignInRoute
  '/_authenticated/panel/': typeof AuthenticatedPanelIndexRoute
  '/_authenticated/user/': typeof AuthenticatedUserIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth/sign-in' | '/panel/' | '/user/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth/sign-in' | '/panel' | '/user'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth/sign-in'
    | '/_authenticated/panel/'
    | '/_authenticated/user/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthSignInRoute: typeof AuthSignInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/user/': {
      id: '/_authenticated/user/'
      path: '/user'
      fullPath: '/user/'
      preLoaderRoute: typeof AuthenticatedUserIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/panel/': {
      id: '/_authenticated/panel/'
      path: '/panel'
      fullPath: '/panel/'
      preLoaderRoute: typeof AuthenticatedPanelIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedPanelIndexRoute: typeof AuthenticatedPanelIndexRoute
  AuthenticatedUserIndexRoute: typeof AuthenticatedUserIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedPanelIndexRoute: AuthenticatedPanelIndexRoute,
  AuthenticatedUserIndexRoute: AuthenticatedUserIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthSignInRoute: AuthSignInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
